# Generated by Django 2.1.8 on 2019-04-01 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spm_app.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('record_updated', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100, unique=True, validators=[spm_app.custom_validators.validate_alphanumplus])),
                ('file_format', models.CharField(blank=True, max_length=100, validators=[spm_app.custom_validators.validate_alphanumplus])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, validators=[spm_app.custom_validators.validate_alphanumplus])),
            ],
        ),
        migrations.AddIndex(
            model_name='phototag',
            index=models.Index(fields=['tag'], name='spm_app_pho_tag_79e335_idx'),
        ),
        migrations.AddField(
            model_name='photodata',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photodata',
            name='tags',
            field=models.ManyToManyField(blank=True, to='spm_app.PhotoTag'),
        ),
        migrations.AddIndex(
            model_name='photodata',
            index=models.Index(fields=['file_name'], name='spm_app_pho_file_na_a33cdf_idx'),
        ),
    ]
