# Generated by Django 2.1.8 on 2019-04-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photodata',
            old_name='public_url',
            new_name='public_root_img',
        ),
    ]
