# Generated by Django 2.1.8 on 2019-04-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0002_auto_20190415_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photodata',
            old_name='public_root_img',
            new_name='public_img_root',
        ),
    ]
