# Generated by Django 2.1.8 on 2019-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0003_auto_20190402_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototag',
            name='tags',
        ),
        migrations.AddField(
            model_name='phototag',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tags', to='spm_app.PhotoData'),
        ),
    ]
