# Generated by Django 2.1.8 on 2019-04-15 19:56

from django.db import migrations, models
import spm_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0003_auto_20190415_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodata',
            name='public_img_root',
            field=models.CharField(max_length=255, validators=[spm_app.custom_validators.validate_url]),
        ),
    ]
