# Generated by Django 2.1.8 on 2019-04-15 22:30

from django.db import migrations, models
import spm_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0004_auto_20190415_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodata',
            name='public_img_tn',
            field=models.CharField(default='/img/tn', max_length=255, validators=[spm_app.custom_validators.validate_url]),
            preserve_default=False,
        ),
    ]
