# Generated by Django 2.1.8 on 2019-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0004_auto_20190402_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodata',
            name='tags',
            field=models.ManyToManyField(to='spm_app.PhotoTag'),
        ),
        migrations.AlterField(
            model_name='phototag',
            name='photos',
            field=models.ManyToManyField(to='spm_app.PhotoData'),
        ),
    ]
