# Generated by Django 2.1.8 on 2019-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0005_auto_20190402_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototag',
            name='photos',
        ),
        migrations.AlterField(
            model_name='photodata',
            name='tags',
            field=models.ManyToManyField(related_name='photo_data', to='spm_app.PhotoTag'),
        ),
    ]
