# Generated by Django 2.1.8 on 2019-04-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0005_photodata_public_img_tn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photodata',
            old_name='public_img_root',
            new_name='public_img_tn_url',
        ),
        migrations.RenameField(
            model_name='photodata',
            old_name='public_img_tn',
            new_name='public_img_url',
        ),
    ]
