# Generated by Django 2.1.8 on 2019-04-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0006_auto_20190402_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phototag',
            options={'ordering': ('tag',)},
        ),
    ]
