# Generated by Django 2.1.8 on 2019-04-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0007_auto_20190417_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photodata',
            options={'ordering': ('id', 'original_url')},
        ),
    ]
