# Generated by Django 2.1.8 on 2019-04-03 23:44

from django.db import migrations, models
import spm_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0007_auto_20190402_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodata',
            name='original_url',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[spm_app.custom_validators.validate_url]),
        ),
        migrations.AddField(
            model_name='photodata',
            name='processed_url',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[spm_app.custom_validators.validate_url]),
        ),
    ]
