# Generated by Django 2.1.8 on 2019-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0008_auto_20190417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodata',
            name='mod_lock',
            field=models.BooleanField(default=False),
        ),
    ]
