# Generated by Django 2.1.8 on 2019-04-04 01:05

from django.db import migrations, models
import spm_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0008_auto_20190403_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='tag',
            field=models.CharField(blank=True, max_length=100, unique=True, validators=[spm_app.custom_validators.validate_alphanumplus]),
        ),
    ]
