# Generated by Django 2.2.4 on 2019-10-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0009_photodata_mod_lock'),
        ('spm_app', '0009_auto_20190404_0105'),
    ]

    operations = [
    ]
