# Generated by Django 2.1.8 on 2019-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0010_auto_20190408_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodata',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photo_data', to='spm_app.PhotoTag'),
        ),
    ]
