# Generated by Django 3.0.1 on 2020-01-13 13:11

from django.db import migrations, models
import spm_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('spm_app', '0010_merge_20191010_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='group_access',
            field=models.ManyToManyField(null=True, related_name='group_access', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='original_url',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[spm_app.custom_validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='processed_url',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[spm_app.custom_validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photo_data', to='spm_app.PhotoTag'),
        ),
    ]
