# Generated by Django 2.1.8 on 2019-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0011_auto_20190408_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodata',
            name='original_url',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
