# Generated by Django 3.0.1 on 2020-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('spm_app', '0011_auto_20200113_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='group_access',
            field=models.ManyToManyField(related_name='group_access', to='auth.Group'),
        ),
    ]
