# Generated by Django 2.1.8 on 2019-04-10 15:34

from django.db import migrations, models
import spm_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('spm_app', '0012_auto_20190408_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodata',
            name='original_url',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[spm_app.custom_validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='processed_url',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[spm_app.custom_validators.validate_url]),
        ),
    ]
