# Generated by Django 3.0.1 on 2020-01-13 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spm_app', '0013_auto_20200113_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='user_access',
            field=models.ManyToManyField(blank=True, related_name='user_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
